//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.openmicroscopy.org/Schemas/OME/2016-06}Settings"&gt;
 *       &lt;attribute name="ID" use="required" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}DetectorID" /&gt;
 *       &lt;attribute name="Offset" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="Gain" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="Voltage" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="VoltageUnit" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}UnitsElectricPotential" default="V" /&gt;
 *       &lt;attribute name="Zoom" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="ReadOutRate" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="ReadOutRateUnit" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}UnitsFrequency" default="MHz" /&gt;
 *       &lt;attribute name="Binning" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}Binning" /&gt;
 *       &lt;attribute name="Integration" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}PositiveInt" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DetectorSettings")
public class DetectorSettings
    extends Settings
{

    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "Offset")
    protected Float offset;
    @XmlAttribute(name = "Gain")
    protected Float gain;
    @XmlAttribute(name = "Voltage")
    protected Float voltage;
    @XmlAttribute(name = "VoltageUnit")
    protected UnitsElectricPotential voltageUnit;
    @XmlAttribute(name = "Zoom")
    protected Float zoom;
    @XmlAttribute(name = "ReadOutRate")
    protected Float readOutRate;
    @XmlAttribute(name = "ReadOutRateUnit")
    protected String readOutRateUnit;
    @XmlAttribute(name = "Binning")
    protected String binning;
    @XmlAttribute(name = "Integration")
    protected Integer integration;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setOffset(Float value) {
        this.offset = value;
    }

    /**
     * Gets the value of the gain property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getGain() {
        return gain;
    }

    /**
     * Sets the value of the gain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setGain(Float value) {
        this.gain = value;
    }

    /**
     * Gets the value of the voltage property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVoltage() {
        return voltage;
    }

    /**
     * Sets the value of the voltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVoltage(Float value) {
        this.voltage = value;
    }

    /**
     * Gets the value of the voltageUnit property.
     * 
     * @return
     *     possible object is
     *     {@link UnitsElectricPotential }
     *     
     */
    public UnitsElectricPotential getVoltageUnit() {
        if (voltageUnit == null) {
            return UnitsElectricPotential.V;
        } else {
            return voltageUnit;
        }
    }

    /**
     * Sets the value of the voltageUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitsElectricPotential }
     *     
     */
    public void setVoltageUnit(UnitsElectricPotential value) {
        this.voltageUnit = value;
    }

    /**
     * Gets the value of the zoom property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getZoom() {
        return zoom;
    }

    /**
     * Sets the value of the zoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setZoom(Float value) {
        this.zoom = value;
    }

    /**
     * Gets the value of the readOutRate property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getReadOutRate() {
        return readOutRate;
    }

    /**
     * Sets the value of the readOutRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setReadOutRate(Float value) {
        this.readOutRate = value;
    }

    /**
     * Gets the value of the readOutRateUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadOutRateUnit() {
        if (readOutRateUnit == null) {
            return "MHz";
        } else {
            return readOutRateUnit;
        }
    }

    /**
     * Sets the value of the readOutRateUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadOutRateUnit(String value) {
        this.readOutRateUnit = value;
    }

    /**
     * Gets the value of the binning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBinning() {
        return binning;
    }

    /**
     * Sets the value of the binning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinning(String value) {
        this.binning = value;
    }

    /**
     * Gets the value of the integration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIntegration() {
        return integration;
    }

    /**
     * Sets the value of the integration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIntegration(Integer value) {
        this.integration = value;
    }

}
