//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.openmicroscopy.org/Schemas/OME/2016-06}ManufacturerSpec"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}AnnotationRef" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Gain" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="Voltage" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="VoltageUnit" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}UnitsElectricPotential" default="V" /&gt;
 *       &lt;attribute name="Offset" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="Zoom" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="AmplificationGain" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="ID" use="required" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}DetectorID" /&gt;
 *       &lt;attribute name="Type"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="CCD"/&gt;
 *             &lt;enumeration value="IntensifiedCCD"/&gt;
 *             &lt;enumeration value="AnalogVideo"/&gt;
 *             &lt;enumeration value="PMT"/&gt;
 *             &lt;enumeration value="Photodiode"/&gt;
 *             &lt;enumeration value="Spectroscopy"/&gt;
 *             &lt;enumeration value="LifetimeImaging"/&gt;
 *             &lt;enumeration value="CorrelationSpectroscopy"/&gt;
 *             &lt;enumeration value="FTIR"/&gt;
 *             &lt;enumeration value="EMCCD"/&gt;
 *             &lt;enumeration value="APD"/&gt;
 *             &lt;enumeration value="CMOS"/&gt;
 *             &lt;enumeration value="EBCCD"/&gt;
 *             &lt;enumeration value="Other"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "annotationRef"
})
@XmlRootElement(name = "Detector")
public class Detector
    extends ManufacturerSpec
{

    @XmlElement(name = "AnnotationRef")
    protected List<AnnotationRef> annotationRef;
    @XmlAttribute(name = "Gain")
    protected Float gain;
    @XmlAttribute(name = "Voltage")
    protected Float voltage;
    @XmlAttribute(name = "VoltageUnit")
    protected UnitsElectricPotential voltageUnit;
    @XmlAttribute(name = "Offset")
    protected Float offset;
    @XmlAttribute(name = "Zoom")
    protected Float zoom;
    @XmlAttribute(name = "AmplificationGain")
    protected Float amplificationGain;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "Type")
    protected String type;

    /**
     * Gets the value of the annotationRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotationRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotationRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnotationRef }
     * 
     * 
     */
    public List<AnnotationRef> getAnnotationRef() {
        if (annotationRef == null) {
            annotationRef = new ArrayList<AnnotationRef>();
        }
        return this.annotationRef;
    }

    /**
     * Gets the value of the gain property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getGain() {
        return gain;
    }

    /**
     * Sets the value of the gain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setGain(Float value) {
        this.gain = value;
    }

    /**
     * Gets the value of the voltage property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVoltage() {
        return voltage;
    }

    /**
     * Sets the value of the voltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVoltage(Float value) {
        this.voltage = value;
    }

    /**
     * Gets the value of the voltageUnit property.
     * 
     * @return
     *     possible object is
     *     {@link UnitsElectricPotential }
     *     
     */
    public UnitsElectricPotential getVoltageUnit() {
        if (voltageUnit == null) {
            return UnitsElectricPotential.V;
        } else {
            return voltageUnit;
        }
    }

    /**
     * Sets the value of the voltageUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitsElectricPotential }
     *     
     */
    public void setVoltageUnit(UnitsElectricPotential value) {
        this.voltageUnit = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setOffset(Float value) {
        this.offset = value;
    }

    /**
     * Gets the value of the zoom property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getZoom() {
        return zoom;
    }

    /**
     * Sets the value of the zoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setZoom(Float value) {
        this.zoom = value;
    }

    /**
     * Gets the value of the amplificationGain property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAmplificationGain() {
        return amplificationGain;
    }

    /**
     * Sets the value of the amplificationGain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAmplificationGain(Float value) {
        this.amplificationGain = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
