//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.openmicroscopy.org/Schemas/OME/2016-06}TypeAnnotation"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}BinaryFile"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "binaryFile"
})
@XmlRootElement(name = "FileAnnotation")
public class FileAnnotation
    extends TypeAnnotation
{

    @XmlElement(name = "BinaryFile", required = true)
    protected BinaryFile binaryFile;

    /**
     * Gets the value of the binaryFile property.
     * 
     * @return
     *     possible object is
     *     {@link BinaryFile }
     *     
     */
    public BinaryFile getBinaryFile() {
        return binaryFile;
    }

    /**
     * Sets the value of the binaryFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link BinaryFile }
     *     
     */
    public void setBinaryFile(BinaryFile value) {
        this.binaryFile = value;
    }

}
