//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.openmicroscopy.org/Schemas/OME/2016-06}ManufacturerSpec"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}TransmittanceRange" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}AnnotationRef" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Type"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Dichroic"/&gt;
 *             &lt;enumeration value="LongPass"/&gt;
 *             &lt;enumeration value="ShortPass"/&gt;
 *             &lt;enumeration value="BandPass"/&gt;
 *             &lt;enumeration value="MultiPass"/&gt;
 *             &lt;enumeration value="NeutralDensity"/&gt;
 *             &lt;enumeration value="Tuneable"/&gt;
 *             &lt;enumeration value="Other"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="FilterWheel" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ID" use="required" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}FilterID" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transmittanceRange",
    "annotationRef"
})
@XmlRootElement(name = "Filter")
public class Filter
    extends ManufacturerSpec
{

    @XmlElement(name = "TransmittanceRange")
    protected TransmittanceRange transmittanceRange;
    @XmlElement(name = "AnnotationRef")
    protected List<AnnotationRef> annotationRef;
    @XmlAttribute(name = "Type")
    protected String type;
    @XmlAttribute(name = "FilterWheel")
    protected String filterWheel;
    @XmlAttribute(name = "ID", required = true)
    protected String id;

    /**
     * Gets the value of the transmittanceRange property.
     * 
     * @return
     *     possible object is
     *     {@link TransmittanceRange }
     *     
     */
    public TransmittanceRange getTransmittanceRange() {
        return transmittanceRange;
    }

    /**
     * Sets the value of the transmittanceRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransmittanceRange }
     *     
     */
    public void setTransmittanceRange(TransmittanceRange value) {
        this.transmittanceRange = value;
    }

    /**
     * Gets the value of the annotationRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotationRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotationRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnotationRef }
     * 
     * 
     */
    public List<AnnotationRef> getAnnotationRef() {
        if (annotationRef == null) {
            annotationRef = new ArrayList<AnnotationRef>();
        }
        return this.annotationRef;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the filterWheel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilterWheel() {
        return filterWheel;
    }

    /**
     * Sets the value of the filterWheel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilterWheel(String value) {
        this.filterWheel = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
