//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.openmicroscopy.org/Schemas/OME/2016-06}Settings"&gt;
 *       &lt;attribute name="ID" use="required" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}ObjectiveID" /&gt;
 *       &lt;attribute name="CorrectionCollar" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="Medium"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Air"/&gt;
 *             &lt;enumeration value="Oil"/&gt;
 *             &lt;enumeration value="Water"/&gt;
 *             &lt;enumeration value="Glycerol"/&gt;
 *             &lt;enumeration value="Other"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="RefractiveIndex" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ObjectiveSettings")
public class ObjectiveSettings
    extends Settings
{

    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "CorrectionCollar")
    protected Float correctionCollar;
    @XmlAttribute(name = "Medium")
    protected String medium;
    @XmlAttribute(name = "RefractiveIndex")
    protected Float refractiveIndex;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the correctionCollar property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCorrectionCollar() {
        return correctionCollar;
    }

    /**
     * Sets the value of the correctionCollar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCorrectionCollar(Float value) {
        this.correctionCollar = value;
    }

    /**
     * Gets the value of the medium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedium() {
        return medium;
    }

    /**
     * Sets the value of the medium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedium(String value) {
        this.medium = value;
    }

    /**
     * Gets the value of the refractiveIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRefractiveIndex() {
        return refractiveIndex;
    }

    /**
     * Sets the value of the refractiveIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRefractiveIndex(Float value) {
        this.refractiveIndex = value;
    }

}
