//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PixelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PixelType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="int8"/&gt;
 *     &lt;enumeration value="int16"/&gt;
 *     &lt;enumeration value="int32"/&gt;
 *     &lt;enumeration value="uint8"/&gt;
 *     &lt;enumeration value="uint16"/&gt;
 *     &lt;enumeration value="uint32"/&gt;
 *     &lt;enumeration value="float"/&gt;
 *     &lt;enumeration value="double"/&gt;
 *     &lt;enumeration value="complex"/&gt;
 *     &lt;enumeration value="double-complex"/&gt;
 *     &lt;enumeration value="bit"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PixelType")
@XmlEnum
public enum PixelType {


    /**
     *  8 bit signed integer.
     * 
     */
    @XmlEnumValue("int8")
    INT_8("int8"),

    /**
     *  16 bit signed integer.
     * 
     */
    @XmlEnumValue("int16")
    INT_16("int16"),

    /**
     *  32 bit signed integer.
     * 
     */
    @XmlEnumValue("int32")
    INT_32("int32"),

    /**
     *  8 bit unsigned integer.
     * 
     */
    @XmlEnumValue("uint8")
    UINT_8("uint8"),

    /**
     *  16 bit unsigned integer.
     * 
     */
    @XmlEnumValue("uint16")
    UINT_16("uint16"),

    /**
     *  32 bit unsigned integer.
     * 
     */
    @XmlEnumValue("uint32")
    UINT_32("uint32"),

    /**
     * single-precision floating point.
     * 
     */
    @XmlEnumValue("float")
    FLOAT("float"),

    /**
     * double-precision floating point.
     * 
     */
    @XmlEnumValue("double")
    DOUBLE("double"),

    /**
     * complex single-precision floating point.
     * 
     */
    @XmlEnumValue("complex")
    COMPLEX("complex"),

    /**
     * complex double-precision floating point.
     * 
     */
    @XmlEnumValue("double-complex")
    DOUBLE_COMPLEX("double-complex"),

    /**
     * bit mask.
     * 
     */
    @XmlEnumValue("bit")
    BIT("bit");
    private final String value;

    PixelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PixelType fromValue(String v) {
        for (PixelType c: PixelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
