//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Reference is an empty complex type that is contained and extended by all the *Ref elements and also the Settings Complex Type
 *         Each *Ref element defines an attribute named ID of simple type *ID and no other information
 *         Each simple type *ID is restricted to the base type LSID with an appropriate pattern
 *       
 * 
 * <p>Java class for Reference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Reference"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reference")
@XmlSeeAlso({
    org.openmicroscopy.schemas.ome._2016_06.Screen.PlateRef.class,
    FilterRef.class,
    ProjectRef.class,
    ChannelRef.class,
    Pump.class,
    MicrobeamManipulationRef.class,
    FilterSetRef.class,
    InstrumentRef.class,
    ExperimentRef.class,
    DichroicRef.class,
    Leader.class,
    WellSampleRef.class,
    ReagentRef.class,
    Settings.class,
    ROIRef.class,
    FolderRef.class,
    ImageRef.class,
    AnnotationRef.class,
    DatasetRef.class,
    ExperimenterGroupRef.class,
    ExperimenterRef.class
})
public class Reference {


}
