//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Settings is an empty complex type that is contained and extended by all the *Settings elements
 *         Each *Settings element defines an attribute named ID of simple type *ID and the other information that is needed.
 *         Each simple type *ID is restricted to the base type LSID with an appropriate pattern
 *       
 * 
 * <p>Java class for Settings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Settings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.openmicroscopy.org/Schemas/OME/2016-06}Reference"&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Settings")
@XmlSeeAlso({
    DetectorSettings.class,
    ObjectiveSettings.class,
    LightSourceSettings.class
})
public class Settings
    extends Reference
{


}
