//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitsTemperature.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnitsTemperature"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="°C"/&gt;
 *     &lt;enumeration value="°F"/&gt;
 *     &lt;enumeration value="K"/&gt;
 *     &lt;enumeration value="°R"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "UnitsTemperature")
@XmlEnum
public enum UnitsTemperature {


    /**
     * degree Celsius unit.
     * 
     */
    @XmlEnumValue("\u00b0C")
    C("\u00b0C"),

    /**
     * degree Fahrenheit unit.
     * 
     */
    @XmlEnumValue("\u00b0F")
    F("\u00b0F"),

    /**
     * Kelvin unit.
     * 
     */
    K("K"),

    /**
     * degree Rankine unit.
     * 
     */
    @XmlEnumValue("\u00b0R")
    R("\u00b0R");
    private final String value;

    UnitsTemperature(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UnitsTemperature fromValue(String v) {
        for (UnitsTemperature c: UnitsTemperature.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
