//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitsAngle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnitsAngle"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="deg"/&gt;
 *     &lt;enumeration value="rad"/&gt;
 *     &lt;enumeration value="gon"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "UnitsAngle")
@XmlEnum
public enum UnitsAngle {


    /**
     * degree unit.
     * 
     */
    @XmlEnumValue("deg")
    DEG("deg"),

    /**
     * radian unit.
     * 
     */
    @XmlEnumValue("rad")
    RAD("rad"),

    /**
     * gradian unit.
     * 
     */
    @XmlEnumValue("gon")
    GON("gon");
    private final String value;

    UnitsAngle(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UnitsAngle fromValue(String v) {
        for (UnitsAngle c: UnitsAngle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
