//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitsElectricPotential.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnitsElectricPotential"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="YV"/&gt;
 *     &lt;enumeration value="ZV"/&gt;
 *     &lt;enumeration value="EV"/&gt;
 *     &lt;enumeration value="PV"/&gt;
 *     &lt;enumeration value="TV"/&gt;
 *     &lt;enumeration value="GV"/&gt;
 *     &lt;enumeration value="MV"/&gt;
 *     &lt;enumeration value="kV"/&gt;
 *     &lt;enumeration value="hV"/&gt;
 *     &lt;enumeration value="daV"/&gt;
 *     &lt;enumeration value="V"/&gt;
 *     &lt;enumeration value="dV"/&gt;
 *     &lt;enumeration value="cV"/&gt;
 *     &lt;enumeration value="mV"/&gt;
 *     &lt;enumeration value="µV"/&gt;
 *     &lt;enumeration value="nV"/&gt;
 *     &lt;enumeration value="pV"/&gt;
 *     &lt;enumeration value="fV"/&gt;
 *     &lt;enumeration value="aV"/&gt;
 *     &lt;enumeration value="zV"/&gt;
 *     &lt;enumeration value="yV"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "UnitsElectricPotential")
@XmlEnum
public enum UnitsElectricPotential {


    /**
     * yottavolt unit.
     * 
     */
    YV("YV"),

    /**
     * zettavolt unit.
     * 
     */
    ZV("ZV"),

    /**
     * exavolt unit.
     * 
     */
    EV("EV"),

    /**
     * petavolt unit.
     * 
     */
    PV("PV"),

    /**
     * teravolt unit.
     * 
     */
    TV("TV"),

    /**
     * gigavolt unit.
     * 
     */
    GV("GV"),

    /**
     * megavolt unit.
     * 
     */
    MV("MV"),

    /**
     * kilovolt unit.
     * 
     */
    @XmlEnumValue("kV")
    K_V("kV"),

    /**
     * hectovolt unit.
     * 
     */
    @XmlEnumValue("hV")
    H_V("hV"),

    /**
     * decavolt unit.
     * 
     */
    @XmlEnumValue("daV")
    DA_V("daV"),

    /**
     * volt unit.
     * 
     */
    V("V"),

    /**
     * decivolt unit.
     * 
     */
    @XmlEnumValue("dV")
    D_V("dV"),

    /**
     * centivolt unit.
     * 
     */
    @XmlEnumValue("cV")
    C_V("cV"),

    /**
     * millivolt unit.
     * 
     */
    @XmlEnumValue("mV")
    M_V("mV"),

    /**
     * microvolt unit.
     * 
     */
    @XmlEnumValue("\u00b5V")
    Μ_V("\u00b5V"),

    /**
     * nanovolt unit.
     * 
     */
    @XmlEnumValue("nV")
    N_V("nV"),

    /**
     * picovolt unit.
     * 
     */
    @XmlEnumValue("pV")
    P_V("pV"),

    /**
     * femtovolt unit.
     * 
     */
    @XmlEnumValue("fV")
    F_V("fV"),

    /**
     * attovolt unit.
     * 
     */
    @XmlEnumValue("aV")
    A_V("aV"),

    /**
     * zeptovolt unit.
     * 
     */
    @XmlEnumValue("zV")
    Z_V("zV"),

    /**
     * yoctovolt unit.
     * 
     */
    @XmlEnumValue("yV")
    Y_V("yV");
    private final String value;

    UnitsElectricPotential(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UnitsElectricPotential fromValue(String v) {
        for (UnitsElectricPotential c: UnitsElectricPotential.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
