//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}LightSourceSettings" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}DetectorSettings" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}FilterSetRef" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}AnnotationRef" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}LightPath" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ID" use="required" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}ChannelID" /&gt;
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SamplesPerPixel" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}PositiveInt" /&gt;
 *       &lt;attribute name="IlluminationType"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Transmitted"/&gt;
 *             &lt;enumeration value="Epifluorescence"/&gt;
 *             &lt;enumeration value="Oblique"/&gt;
 *             &lt;enumeration value="NonLinear"/&gt;
 *             &lt;enumeration value="Other"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="PinholeSize" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="PinholeSizeUnit" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}UnitsLength" default="µm" /&gt;
 *       &lt;attribute name="AcquisitionMode"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="WideField"/&gt;
 *             &lt;enumeration value="LaserScanningConfocalMicroscopy"/&gt;
 *             &lt;enumeration value="SpinningDiskConfocal"/&gt;
 *             &lt;enumeration value="SlitScanConfocal"/&gt;
 *             &lt;enumeration value="MultiPhotonMicroscopy"/&gt;
 *             &lt;enumeration value="StructuredIllumination"/&gt;
 *             &lt;enumeration value="SingleMoleculeImaging"/&gt;
 *             &lt;enumeration value="TotalInternalReflection"/&gt;
 *             &lt;enumeration value="FluorescenceLifetime"/&gt;
 *             &lt;enumeration value="SpectralImaging"/&gt;
 *             &lt;enumeration value="FluorescenceCorrelationSpectroscopy"/&gt;
 *             &lt;enumeration value="NearFieldScanningOpticalMicroscopy"/&gt;
 *             &lt;enumeration value="SecondHarmonicGenerationImaging"/&gt;
 *             &lt;enumeration value="PALM"/&gt;
 *             &lt;enumeration value="STORM"/&gt;
 *             &lt;enumeration value="STED"/&gt;
 *             &lt;enumeration value="TIRF"/&gt;
 *             &lt;enumeration value="FSM"/&gt;
 *             &lt;enumeration value="LCM"/&gt;
 *             &lt;enumeration value="Other"/&gt;
 *             &lt;enumeration value="BrightField"/&gt;
 *             &lt;enumeration value="SweptFieldConfocal"/&gt;
 *             &lt;enumeration value="SPIM"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ContrastMethod"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Brightfield"/&gt;
 *             &lt;enumeration value="Phase"/&gt;
 *             &lt;enumeration value="DIC"/&gt;
 *             &lt;enumeration value="HoffmanModulation"/&gt;
 *             &lt;enumeration value="ObliqueIllumination"/&gt;
 *             &lt;enumeration value="PolarizedLight"/&gt;
 *             &lt;enumeration value="Darkfield"/&gt;
 *             &lt;enumeration value="Fluorescence"/&gt;
 *             &lt;enumeration value="Other"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ExcitationWavelength" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}PositiveFloat" /&gt;
 *       &lt;attribute name="ExcitationWavelengthUnit" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}UnitsLength" default="nm" /&gt;
 *       &lt;attribute name="EmissionWavelength" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}PositiveFloat" /&gt;
 *       &lt;attribute name="EmissionWavelengthUnit" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}UnitsLength" default="nm" /&gt;
 *       &lt;attribute name="Fluor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NDFilter" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="PockelCellSetting" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="Color" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}Color" default="-1" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lightSourceSettings",
    "detectorSettings",
    "filterSetRef",
    "annotationRef",
    "lightPath"
})
@XmlRootElement(name = "Channel")
public class Channel {

    @XmlElement(name = "LightSourceSettings")
    protected LightSourceSettings lightSourceSettings;
    @XmlElement(name = "DetectorSettings")
    protected DetectorSettings detectorSettings;
    @XmlElement(name = "FilterSetRef")
    protected FilterSetRef filterSetRef;
    @XmlElement(name = "AnnotationRef")
    protected List<AnnotationRef> annotationRef;
    @XmlElement(name = "LightPath")
    protected LightPath lightPath;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "Name")
    protected String name;
    @XmlAttribute(name = "SamplesPerPixel")
    protected Integer samplesPerPixel;
    @XmlAttribute(name = "IlluminationType")
    protected String illuminationType;
    @XmlAttribute(name = "PinholeSize")
    protected Float pinholeSize;
    @XmlAttribute(name = "PinholeSizeUnit")
    protected String pinholeSizeUnit;
    @XmlAttribute(name = "AcquisitionMode")
    protected String acquisitionMode;
    @XmlAttribute(name = "ContrastMethod")
    protected String contrastMethod;
    @XmlAttribute(name = "ExcitationWavelength")
    protected Float excitationWavelength;
    @XmlAttribute(name = "ExcitationWavelengthUnit")
    protected String excitationWavelengthUnit;
    @XmlAttribute(name = "EmissionWavelength")
    protected Float emissionWavelength;
    @XmlAttribute(name = "EmissionWavelengthUnit")
    protected String emissionWavelengthUnit;
    @XmlAttribute(name = "Fluor")
    protected String fluor;
    @XmlAttribute(name = "NDFilter")
    protected Float ndFilter;
    @XmlAttribute(name = "PockelCellSetting")
    protected Integer pockelCellSetting;
    @XmlAttribute(name = "Color")
    protected Integer color;

    /**
     * Gets the value of the lightSourceSettings property.
     * 
     * @return
     *     possible object is
     *     {@link LightSourceSettings }
     *     
     */
    public LightSourceSettings getLightSourceSettings() {
        return lightSourceSettings;
    }

    /**
     * Sets the value of the lightSourceSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link LightSourceSettings }
     *     
     */
    public void setLightSourceSettings(LightSourceSettings value) {
        this.lightSourceSettings = value;
    }

    /**
     * Gets the value of the detectorSettings property.
     * 
     * @return
     *     possible object is
     *     {@link DetectorSettings }
     *     
     */
    public DetectorSettings getDetectorSettings() {
        return detectorSettings;
    }

    /**
     * Sets the value of the detectorSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetectorSettings }
     *     
     */
    public void setDetectorSettings(DetectorSettings value) {
        this.detectorSettings = value;
    }

    /**
     * Gets the value of the filterSetRef property.
     * 
     * @return
     *     possible object is
     *     {@link FilterSetRef }
     *     
     */
    public FilterSetRef getFilterSetRef() {
        return filterSetRef;
    }

    /**
     * Sets the value of the filterSetRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterSetRef }
     *     
     */
    public void setFilterSetRef(FilterSetRef value) {
        this.filterSetRef = value;
    }

    /**
     * Gets the value of the annotationRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotationRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotationRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnotationRef }
     * 
     * 
     */
    public List<AnnotationRef> getAnnotationRef() {
        if (annotationRef == null) {
            annotationRef = new ArrayList<AnnotationRef>();
        }
        return this.annotationRef;
    }

    /**
     * Gets the value of the lightPath property.
     * 
     * @return
     *     possible object is
     *     {@link LightPath }
     *     
     */
    public LightPath getLightPath() {
        return lightPath;
    }

    /**
     * Sets the value of the lightPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link LightPath }
     *     
     */
    public void setLightPath(LightPath value) {
        this.lightPath = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the samplesPerPixel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSamplesPerPixel() {
        return samplesPerPixel;
    }

    /**
     * Sets the value of the samplesPerPixel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSamplesPerPixel(Integer value) {
        this.samplesPerPixel = value;
    }

    /**
     * Gets the value of the illuminationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIlluminationType() {
        return illuminationType;
    }

    /**
     * Sets the value of the illuminationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIlluminationType(String value) {
        this.illuminationType = value;
    }

    /**
     * Gets the value of the pinholeSize property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPinholeSize() {
        return pinholeSize;
    }

    /**
     * Sets the value of the pinholeSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPinholeSize(Float value) {
        this.pinholeSize = value;
    }

    /**
     * Gets the value of the pinholeSizeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinholeSizeUnit() {
        if (pinholeSizeUnit == null) {
            return "\u00b5m";
        } else {
            return pinholeSizeUnit;
        }
    }

    /**
     * Sets the value of the pinholeSizeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinholeSizeUnit(String value) {
        this.pinholeSizeUnit = value;
    }

    /**
     * Gets the value of the acquisitionMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquisitionMode() {
        return acquisitionMode;
    }

    /**
     * Sets the value of the acquisitionMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquisitionMode(String value) {
        this.acquisitionMode = value;
    }

    /**
     * Gets the value of the contrastMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContrastMethod() {
        return contrastMethod;
    }

    /**
     * Sets the value of the contrastMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContrastMethod(String value) {
        this.contrastMethod = value;
    }

    /**
     * Gets the value of the excitationWavelength property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getExcitationWavelength() {
        return excitationWavelength;
    }

    /**
     * Sets the value of the excitationWavelength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setExcitationWavelength(Float value) {
        this.excitationWavelength = value;
    }

    /**
     * Gets the value of the excitationWavelengthUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcitationWavelengthUnit() {
        if (excitationWavelengthUnit == null) {
            return "nm";
        } else {
            return excitationWavelengthUnit;
        }
    }

    /**
     * Sets the value of the excitationWavelengthUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcitationWavelengthUnit(String value) {
        this.excitationWavelengthUnit = value;
    }

    /**
     * Gets the value of the emissionWavelength property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getEmissionWavelength() {
        return emissionWavelength;
    }

    /**
     * Sets the value of the emissionWavelength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setEmissionWavelength(Float value) {
        this.emissionWavelength = value;
    }

    /**
     * Gets the value of the emissionWavelengthUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmissionWavelengthUnit() {
        if (emissionWavelengthUnit == null) {
            return "nm";
        } else {
            return emissionWavelengthUnit;
        }
    }

    /**
     * Sets the value of the emissionWavelengthUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmissionWavelengthUnit(String value) {
        this.emissionWavelengthUnit = value;
    }

    /**
     * Gets the value of the fluor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFluor() {
        return fluor;
    }

    /**
     * Sets the value of the fluor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFluor(String value) {
        this.fluor = value;
    }

    /**
     * Gets the value of the ndFilter property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getNDFilter() {
        return ndFilter;
    }

    /**
     * Sets the value of the ndFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNDFilter(Float value) {
        this.ndFilter = value;
    }

    /**
     * Gets the value of the pockelCellSetting property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPockelCellSetting() {
        return pockelCellSetting;
    }

    /**
     * Sets the value of the pockelCellSetting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPockelCellSetting(Integer value) {
        this.pockelCellSetting = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getColor() {
        if (color == null) {
            return -1;
        } else {
            return color;
        }
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setColor(Integer value) {
        this.color = value;
    }

}
