//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.openmicroscopy.org/Schemas/OME/2016-06}ManufacturerSpec"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExcitationFilterRef" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}FilterRef" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}DichroicRef" minOccurs="0"/&gt;
 *         &lt;element name="EmissionFilterRef" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}FilterRef" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ID" use="required" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}FilterSetID" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "excitationFilterRef",
    "dichroicRef",
    "emissionFilterRef"
})
@XmlRootElement(name = "FilterSet")
public class FilterSet
    extends ManufacturerSpec
{

    @XmlElement(name = "ExcitationFilterRef")
    protected List<FilterRef> excitationFilterRef;
    @XmlElement(name = "DichroicRef")
    protected DichroicRef dichroicRef;
    @XmlElement(name = "EmissionFilterRef")
    protected List<FilterRef> emissionFilterRef;
    @XmlAttribute(name = "ID", required = true)
    protected String id;

    /**
     * Gets the value of the excitationFilterRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the excitationFilterRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExcitationFilterRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FilterRef }
     * 
     * 
     */
    public List<FilterRef> getExcitationFilterRef() {
        if (excitationFilterRef == null) {
            excitationFilterRef = new ArrayList<FilterRef>();
        }
        return this.excitationFilterRef;
    }

    /**
     * Gets the value of the dichroicRef property.
     * 
     * @return
     *     possible object is
     *     {@link DichroicRef }
     *     
     */
    public DichroicRef getDichroicRef() {
        return dichroicRef;
    }

    /**
     * Sets the value of the dichroicRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DichroicRef }
     *     
     */
    public void setDichroicRef(DichroicRef value) {
        this.dichroicRef = value;
    }

    /**
     * Gets the value of the emissionFilterRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emissionFilterRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmissionFilterRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FilterRef }
     * 
     * 
     */
    public List<FilterRef> getEmissionFilterRef() {
        if (emissionFilterRef == null) {
            emissionFilterRef = new ArrayList<FilterRef>();
        }
        return this.emissionFilterRef;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
