//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FontFamily.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FontFamily"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="serif"/&gt;
 *     &lt;enumeration value="sans-serif"/&gt;
 *     &lt;enumeration value="cursive"/&gt;
 *     &lt;enumeration value="fantasy"/&gt;
 *     &lt;enumeration value="monospace"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FontFamily")
@XmlEnum
public enum FontFamily {


    /**
     * serif.
     * 
     */
    @XmlEnumValue("serif")
    SERIF("serif"),

    /**
     * sans-serif.
     * 
     */
    @XmlEnumValue("sans-serif")
    SANS_SERIF("sans-serif"),

    /**
     * cursive.
     * 
     */
    @XmlEnumValue("cursive")
    CURSIVE("cursive"),

    /**
     * fantasy.
     * 
     */
    @XmlEnumValue("fantasy")
    FANTASY("fantasy"),

    /**
     * monospace.
     * 
     */
    @XmlEnumValue("monospace")
    MONOSPACE("monospace");
    private final String value;

    FontFamily(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FontFamily fromValue(String v) {
        for (FontFamily c: FontFamily.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
