//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AcquisitionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}ExperimenterRef" minOccurs="0"/&gt;
 *         &lt;element name="Description" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;whiteSpace value="preserve"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}ExperimentRef" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}ExperimenterGroupRef" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}InstrumentRef" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}ObjectiveSettings" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}ImagingEnvironment" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}StageLabel" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}Pixels"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}ROIRef" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}MicrobeamManipulationRef" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}AnnotationRef" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ID" use="required" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}ImageID" /&gt;
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acquisitionDate",
    "experimenterRef",
    "description",
    "experimentRef",
    "experimenterGroupRef",
    "instrumentRef",
    "objectiveSettings",
    "imagingEnvironment",
    "stageLabel",
    "pixels",
    "roiRef",
    "microbeamManipulationRef",
    "annotationRef"
})
@XmlRootElement(name = "Image")
public class Image {

    @XmlElement(name = "AcquisitionDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar acquisitionDate;
    @XmlElement(name = "ExperimenterRef")
    protected ExperimenterRef experimenterRef;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "ExperimentRef")
    protected ExperimentRef experimentRef;
    @XmlElement(name = "ExperimenterGroupRef")
    protected ExperimenterGroupRef experimenterGroupRef;
    @XmlElement(name = "InstrumentRef")
    protected InstrumentRef instrumentRef;
    @XmlElement(name = "ObjectiveSettings")
    protected ObjectiveSettings objectiveSettings;
    @XmlElement(name = "ImagingEnvironment")
    protected ImagingEnvironment imagingEnvironment;
    @XmlElement(name = "StageLabel")
    protected StageLabel stageLabel;
    @XmlElement(name = "Pixels", required = true)
    protected Pixels pixels;
    @XmlElement(name = "ROIRef")
    protected List<ROIRef> roiRef;
    @XmlElement(name = "MicrobeamManipulationRef")
    protected List<MicrobeamManipulationRef> microbeamManipulationRef;
    @XmlElement(name = "AnnotationRef")
    protected List<AnnotationRef> annotationRef;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "Name")
    protected String name;

    /**
     * Gets the value of the acquisitionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAcquisitionDate() {
        return acquisitionDate;
    }

    /**
     * Sets the value of the acquisitionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcquisitionDate(XMLGregorianCalendar value) {
        this.acquisitionDate = value;
    }

    /**
     * Gets the value of the experimenterRef property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimenterRef }
     *     
     */
    public ExperimenterRef getExperimenterRef() {
        return experimenterRef;
    }

    /**
     * Sets the value of the experimenterRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimenterRef }
     *     
     */
    public void setExperimenterRef(ExperimenterRef value) {
        this.experimenterRef = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the experimentRef property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentRef }
     *     
     */
    public ExperimentRef getExperimentRef() {
        return experimentRef;
    }

    /**
     * Sets the value of the experimentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentRef }
     *     
     */
    public void setExperimentRef(ExperimentRef value) {
        this.experimentRef = value;
    }

    /**
     * Gets the value of the experimenterGroupRef property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimenterGroupRef }
     *     
     */
    public ExperimenterGroupRef getExperimenterGroupRef() {
        return experimenterGroupRef;
    }

    /**
     * Sets the value of the experimenterGroupRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimenterGroupRef }
     *     
     */
    public void setExperimenterGroupRef(ExperimenterGroupRef value) {
        this.experimenterGroupRef = value;
    }

    /**
     * Gets the value of the instrumentRef property.
     * 
     * @return
     *     possible object is
     *     {@link InstrumentRef }
     *     
     */
    public InstrumentRef getInstrumentRef() {
        return instrumentRef;
    }

    /**
     * Sets the value of the instrumentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstrumentRef }
     *     
     */
    public void setInstrumentRef(InstrumentRef value) {
        this.instrumentRef = value;
    }

    /**
     * Gets the value of the objectiveSettings property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectiveSettings }
     *     
     */
    public ObjectiveSettings getObjectiveSettings() {
        return objectiveSettings;
    }

    /**
     * Sets the value of the objectiveSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectiveSettings }
     *     
     */
    public void setObjectiveSettings(ObjectiveSettings value) {
        this.objectiveSettings = value;
    }

    /**
     * Gets the value of the imagingEnvironment property.
     * 
     * @return
     *     possible object is
     *     {@link ImagingEnvironment }
     *     
     */
    public ImagingEnvironment getImagingEnvironment() {
        return imagingEnvironment;
    }

    /**
     * Sets the value of the imagingEnvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImagingEnvironment }
     *     
     */
    public void setImagingEnvironment(ImagingEnvironment value) {
        this.imagingEnvironment = value;
    }

    /**
     * Gets the value of the stageLabel property.
     * 
     * @return
     *     possible object is
     *     {@link StageLabel }
     *     
     */
    public StageLabel getStageLabel() {
        return stageLabel;
    }

    /**
     * Sets the value of the stageLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link StageLabel }
     *     
     */
    public void setStageLabel(StageLabel value) {
        this.stageLabel = value;
    }

    /**
     * Gets the value of the pixels property.
     * 
     * @return
     *     possible object is
     *     {@link Pixels }
     *     
     */
    public Pixels getPixels() {
        return pixels;
    }

    /**
     * Sets the value of the pixels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pixels }
     *     
     */
    public void setPixels(Pixels value) {
        this.pixels = value;
    }

    /**
     * Gets the value of the roiRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roiRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getROIRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ROIRef }
     * 
     * 
     */
    public List<ROIRef> getROIRef() {
        if (roiRef == null) {
            roiRef = new ArrayList<ROIRef>();
        }
        return this.roiRef;
    }

    /**
     * Gets the value of the microbeamManipulationRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the microbeamManipulationRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMicrobeamManipulationRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MicrobeamManipulationRef }
     * 
     * 
     */
    public List<MicrobeamManipulationRef> getMicrobeamManipulationRef() {
        if (microbeamManipulationRef == null) {
            microbeamManipulationRef = new ArrayList<MicrobeamManipulationRef>();
        }
        return this.microbeamManipulationRef;
    }

    /**
     * Gets the value of the annotationRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotationRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotationRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnotationRef }
     * 
     * 
     */
    public List<AnnotationRef> getAnnotationRef() {
        if (annotationRef == null) {
            annotationRef = new ArrayList<AnnotationRef>();
        }
        return this.annotationRef;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
