//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}Microscope" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}LightSourceGroup" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}Detector" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}Objective" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}FilterSet" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}Filter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}Dichroic" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}AnnotationRef" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ID" use="required" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}InstrumentID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "microscope",
    "lightSourceGroup",
    "detector",
    "objective",
    "filterSet",
    "filter",
    "dichroic",
    "annotationRef"
})
@XmlRootElement(name = "Instrument")
public class Instrument {

    @XmlElement(name = "Microscope")
    protected Microscope microscope;
    @XmlElementRef(name = "LightSourceGroup", namespace = "http://www.openmicroscopy.org/Schemas/OME/2016-06", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends LightSource>> lightSourceGroup;
    @XmlElement(name = "Detector")
    protected List<Detector> detector;
    @XmlElement(name = "Objective")
    protected List<Objective> objective;
    @XmlElement(name = "FilterSet")
    protected List<FilterSet> filterSet;
    @XmlElement(name = "Filter")
    protected List<Filter> filter;
    @XmlElement(name = "Dichroic")
    protected List<Dichroic> dichroic;
    @XmlElement(name = "AnnotationRef")
    protected List<AnnotationRef> annotationRef;
    @XmlAttribute(name = "ID", required = true)
    protected String id;

    /**
     * Gets the value of the microscope property.
     * 
     * @return
     *     possible object is
     *     {@link Microscope }
     *     
     */
    public Microscope getMicroscope() {
        return microscope;
    }

    /**
     * Sets the value of the microscope property.
     * 
     * @param value
     *     allowed object is
     *     {@link Microscope }
     *     
     */
    public void setMicroscope(Microscope value) {
        this.microscope = value;
    }

    /**
     * Gets the value of the lightSourceGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lightSourceGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLightSourceGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link GenericExcitationSource }{@code >}
     * {@link JAXBElement }{@code <}{@link Filament }{@code >}
     * {@link JAXBElement }{@code <}{@link LightEmittingDiode }{@code >}
     * {@link JAXBElement }{@code <}{@link Laser }{@code >}
     * {@link JAXBElement }{@code <}{@link Arc }{@code >}
     * {@link JAXBElement }{@code <}{@link LightSource }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends LightSource>> getLightSourceGroup() {
        if (lightSourceGroup == null) {
            lightSourceGroup = new ArrayList<JAXBElement<? extends LightSource>>();
        }
        return this.lightSourceGroup;
    }

    /**
     * Gets the value of the detector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Detector }
     * 
     * 
     */
    public List<Detector> getDetector() {
        if (detector == null) {
            detector = new ArrayList<Detector>();
        }
        return this.detector;
    }

    /**
     * Gets the value of the objective property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objective property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjective().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Objective }
     * 
     * 
     */
    public List<Objective> getObjective() {
        if (objective == null) {
            objective = new ArrayList<Objective>();
        }
        return this.objective;
    }

    /**
     * Gets the value of the filterSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filterSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilterSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FilterSet }
     * 
     * 
     */
    public List<FilterSet> getFilterSet() {
        if (filterSet == null) {
            filterSet = new ArrayList<FilterSet>();
        }
        return this.filterSet;
    }

    /**
     * Gets the value of the filter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Filter }
     * 
     * 
     */
    public List<Filter> getFilter() {
        if (filter == null) {
            filter = new ArrayList<Filter>();
        }
        return this.filter;
    }

    /**
     * Gets the value of the dichroic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dichroic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDichroic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dichroic }
     * 
     * 
     */
    public List<Dichroic> getDichroic() {
        if (dichroic == null) {
            dichroic = new ArrayList<Dichroic>();
        }
        return this.dichroic;
    }

    /**
     * Gets the value of the annotationRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotationRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotationRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnotationRef }
     * 
     * 
     */
    public List<AnnotationRef> getAnnotationRef() {
        if (annotationRef == null) {
            annotationRef = new ArrayList<AnnotationRef>();
        }
        return this.annotationRef;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
