//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.openmicroscopy.org/Schemas/OME/2016-06}LightSource"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.openmicroscopy.org/Schemas/OME/2016-06}Pump" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Type"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Excimer"/&gt;
 *             &lt;enumeration value="Gas"/&gt;
 *             &lt;enumeration value="MetalVapor"/&gt;
 *             &lt;enumeration value="SolidState"/&gt;
 *             &lt;enumeration value="Dye"/&gt;
 *             &lt;enumeration value="Semiconductor"/&gt;
 *             &lt;enumeration value="FreeElectron"/&gt;
 *             &lt;enumeration value="Other"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="LaserMedium"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Cu"/&gt;
 *             &lt;enumeration value="Ag"/&gt;
 *             &lt;enumeration value="ArFl"/&gt;
 *             &lt;enumeration value="ArCl"/&gt;
 *             &lt;enumeration value="KrFl"/&gt;
 *             &lt;enumeration value="KrCl"/&gt;
 *             &lt;enumeration value="XeFl"/&gt;
 *             &lt;enumeration value="XeCl"/&gt;
 *             &lt;enumeration value="XeBr"/&gt;
 *             &lt;enumeration value="N"/&gt;
 *             &lt;enumeration value="Ar"/&gt;
 *             &lt;enumeration value="Kr"/&gt;
 *             &lt;enumeration value="Xe"/&gt;
 *             &lt;enumeration value="HeNe"/&gt;
 *             &lt;enumeration value="HeCd"/&gt;
 *             &lt;enumeration value="CO"/&gt;
 *             &lt;enumeration value="CO2"/&gt;
 *             &lt;enumeration value="H2O"/&gt;
 *             &lt;enumeration value="HFl"/&gt;
 *             &lt;enumeration value="NdGlass"/&gt;
 *             &lt;enumeration value="NdYAG"/&gt;
 *             &lt;enumeration value="ErGlass"/&gt;
 *             &lt;enumeration value="ErYAG"/&gt;
 *             &lt;enumeration value="HoYLF"/&gt;
 *             &lt;enumeration value="HoYAG"/&gt;
 *             &lt;enumeration value="Ruby"/&gt;
 *             &lt;enumeration value="TiSapphire"/&gt;
 *             &lt;enumeration value="Alexandrite"/&gt;
 *             &lt;enumeration value="Rhodamine6G"/&gt;
 *             &lt;enumeration value="CoumarinC30"/&gt;
 *             &lt;enumeration value="GaAs"/&gt;
 *             &lt;enumeration value="GaAlAs"/&gt;
 *             &lt;enumeration value="EMinus"/&gt;
 *             &lt;enumeration value="Other"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Wavelength" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}PositiveFloat" /&gt;
 *       &lt;attribute name="WavelengthUnit" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}UnitsLength" default="nm" /&gt;
 *       &lt;attribute name="FrequencyMultiplication" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}PositiveInt" /&gt;
 *       &lt;attribute name="Tuneable" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="Pulse"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="CW"/&gt;
 *             &lt;enumeration value="Single"/&gt;
 *             &lt;enumeration value="QSwitched"/&gt;
 *             &lt;enumeration value="Repetitive"/&gt;
 *             &lt;enumeration value="ModeLocked"/&gt;
 *             &lt;enumeration value="Other"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="PockelCell" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="RepetitionRate" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="RepetitionRateUnit" type="{http://www.openmicroscopy.org/Schemas/OME/2016-06}UnitsFrequency" default="Hz" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pump"
})
public class Laser
    extends LightSource
{

    @XmlElement(name = "Pump")
    protected Pump pump;
    @XmlAttribute(name = "Type")
    protected String type;
    @XmlAttribute(name = "LaserMedium")
    protected String laserMedium;
    @XmlAttribute(name = "Wavelength")
    protected Float wavelength;
    @XmlAttribute(name = "WavelengthUnit")
    protected String wavelengthUnit;
    @XmlAttribute(name = "FrequencyMultiplication")
    protected Integer frequencyMultiplication;
    @XmlAttribute(name = "Tuneable")
    protected Boolean tuneable;
    @XmlAttribute(name = "Pulse")
    protected String pulse;
    @XmlAttribute(name = "PockelCell")
    protected Boolean pockelCell;
    @XmlAttribute(name = "RepetitionRate")
    protected Float repetitionRate;
    @XmlAttribute(name = "RepetitionRateUnit")
    protected String repetitionRateUnit;

    /**
     * 
     *                   The Laser element may contain a Pump sub-element which refers to
     *                   a LightSource used as a laser pump.
     *                 
     * 
     * @return
     *     possible object is
     *     {@link Pump }
     *     
     */
    public Pump getPump() {
        return pump;
    }

    /**
     * Sets the value of the pump property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pump }
     *     
     */
    public void setPump(Pump value) {
        this.pump = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the laserMedium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaserMedium() {
        return laserMedium;
    }

    /**
     * Sets the value of the laserMedium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaserMedium(String value) {
        this.laserMedium = value;
    }

    /**
     * Gets the value of the wavelength property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getWavelength() {
        return wavelength;
    }

    /**
     * Sets the value of the wavelength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setWavelength(Float value) {
        this.wavelength = value;
    }

    /**
     * Gets the value of the wavelengthUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWavelengthUnit() {
        if (wavelengthUnit == null) {
            return "nm";
        } else {
            return wavelengthUnit;
        }
    }

    /**
     * Sets the value of the wavelengthUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWavelengthUnit(String value) {
        this.wavelengthUnit = value;
    }

    /**
     * Gets the value of the frequencyMultiplication property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFrequencyMultiplication() {
        return frequencyMultiplication;
    }

    /**
     * Sets the value of the frequencyMultiplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFrequencyMultiplication(Integer value) {
        this.frequencyMultiplication = value;
    }

    /**
     * Gets the value of the tuneable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTuneable() {
        return tuneable;
    }

    /**
     * Sets the value of the tuneable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTuneable(Boolean value) {
        this.tuneable = value;
    }

    /**
     * Gets the value of the pulse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPulse() {
        return pulse;
    }

    /**
     * Sets the value of the pulse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPulse(String value) {
        this.pulse = value;
    }

    /**
     * Gets the value of the pockelCell property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPockelCell() {
        return pockelCell;
    }

    /**
     * Sets the value of the pockelCell property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPockelCell(Boolean value) {
        this.pockelCell = value;
    }

    /**
     * Gets the value of the repetitionRate property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRepetitionRate() {
        return repetitionRate;
    }

    /**
     * Sets the value of the repetitionRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRepetitionRate(Float value) {
        this.repetitionRate = value;
    }

    /**
     * Gets the value of the repetitionRateUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepetitionRateUnit() {
        if (repetitionRateUnit == null) {
            return "Hz";
        } else {
            return repetitionRateUnit;
        }
    }

    /**
     * Sets the value of the repetitionRateUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepetitionRateUnit(String value) {
        this.repetitionRateUnit = value;
    }

}
