//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openmicroscopy.org/Schemas/OME/2016-06", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openmicroscopy.schemas.ome._2016_06;
