//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.24 at 10:51:22 AM UTC 
//


package org.openmicroscopy.schemas.ome._2016_06;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitsPower.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnitsPower"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="YW"/&gt;
 *     &lt;enumeration value="ZW"/&gt;
 *     &lt;enumeration value="EW"/&gt;
 *     &lt;enumeration value="PW"/&gt;
 *     &lt;enumeration value="TW"/&gt;
 *     &lt;enumeration value="GW"/&gt;
 *     &lt;enumeration value="MW"/&gt;
 *     &lt;enumeration value="kW"/&gt;
 *     &lt;enumeration value="hW"/&gt;
 *     &lt;enumeration value="daW"/&gt;
 *     &lt;enumeration value="W"/&gt;
 *     &lt;enumeration value="dW"/&gt;
 *     &lt;enumeration value="cW"/&gt;
 *     &lt;enumeration value="mW"/&gt;
 *     &lt;enumeration value="µW"/&gt;
 *     &lt;enumeration value="nW"/&gt;
 *     &lt;enumeration value="pW"/&gt;
 *     &lt;enumeration value="fW"/&gt;
 *     &lt;enumeration value="aW"/&gt;
 *     &lt;enumeration value="zW"/&gt;
 *     &lt;enumeration value="yW"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "UnitsPower")
@XmlEnum
public enum UnitsPower {


    /**
     * yottawatt unit.
     * 
     */
    YW("YW"),

    /**
     * zettawatt unit.
     * 
     */
    ZW("ZW"),

    /**
     * exawatt unit.
     * 
     */
    EW("EW"),

    /**
     * petawatt unit.
     * 
     */
    PW("PW"),

    /**
     * terawatt unit.
     * 
     */
    TW("TW"),

    /**
     * gigawatt unit.
     * 
     */
    GW("GW"),

    /**
     * megawatt unit.
     * 
     */
    MW("MW"),

    /**
     * kilowatt unit.
     * 
     */
    @XmlEnumValue("kW")
    K_W("kW"),

    /**
     * hectowatt unit.
     * 
     */
    @XmlEnumValue("hW")
    H_W("hW"),

    /**
     * decawatt unit.
     * 
     */
    @XmlEnumValue("daW")
    DA_W("daW"),

    /**
     * watt unit.
     * 
     */
    W("W"),

    /**
     * deciwatt unit.
     * 
     */
    @XmlEnumValue("dW")
    D_W("dW"),

    /**
     * centiwatt unit.
     * 
     */
    @XmlEnumValue("cW")
    C_W("cW"),

    /**
     * milliwatt unit.
     * 
     */
    @XmlEnumValue("mW")
    M_W("mW"),

    /**
     * microwatt unit.
     * 
     */
    @XmlEnumValue("\u00b5W")
    Μ_W("\u00b5W"),

    /**
     * nanowatt unit.
     * 
     */
    @XmlEnumValue("nW")
    N_W("nW"),

    /**
     * picowatt unit.
     * 
     */
    @XmlEnumValue("pW")
    P_W("pW"),

    /**
     * femtowatt unit.
     * 
     */
    @XmlEnumValue("fW")
    F_W("fW"),

    /**
     * attowatt unit.
     * 
     */
    @XmlEnumValue("aW")
    A_W("aW"),

    /**
     * zeptowatt unit.
     * 
     */
    @XmlEnumValue("zW")
    Z_W("zW"),

    /**
     * yoctowatt unit.
     * 
     */
    @XmlEnumValue("yW")
    Y_W("yW");
    private final String value;

    UnitsPower(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UnitsPower fromValue(String v) {
        for (UnitsPower c: UnitsPower.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
